spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  #      routes:
  #        - id:                                        --> asm el service
  #          uri: lb:http://CUSTOMER-SERVICE            --> el endpoint ele hatro7ha bgad
  #          predicates:
  #             - Path=/api/v1/customers/**             -->  el endpoint ele lma t3mlha call tro7 el route dah
  #             - Path=/api/v1/departments/**
        routes:
          - id: demo-service
            uri: lb:http://DEMO-SERVICE
            predicates:
               - Path=/api/v1/demo/**
  #
  #          *****  we law 3ndy service tany copy paste ely fo2 *****
        routes:
          - id: demo-service
            uri: lb:DEMO-SERVICE
            predicates:
              - Path=/api/v1/demo/**

