spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  #      routes:
  #        - id:
  #          uri: lb:http://CUSTOMER-SERVICE
  #          predicates: path=/api/v1/customers/**
server:
  port: 8222
