spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        routes:
          - id: demo-service
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/demo/**

