spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/hrm
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service

server:
  port: 8500

