eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      registerWithEureka: true
      fetchRegistry: true
      defaultZone: http://localhost:8761/eureka
name:
  value: alibou
spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0
