server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee-service
          uri: lb:http://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/v1/employees/**



