server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: demo-service
          uri: lb:http://DEMO-SERVICE
          predicates:
            - Path=/api/v1/demo/**

