server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee-service
          uri: lb:http://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/v1/employees/**
        - id: vacation-service
          uri: lb:http://VACATION-SERVICE
          predicates:
            - Path=/api/v1/vacations/**
        - id: demo-service
          uri: lb:http://DEMO-SERVICE
          predicates:
            - Path=/api/v1/demo/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"  # Your Angular app's origin
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/hrm